### ISSUE TITLE
运行时问题

### ISSUE THREAD

**Issue by EdwardL1u** [liuzhuojin/BookRecommend#1]
启动项目后，首页无内容，网页控制台报错：Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING。

**Comment by han113** [comment]
> 启动项目后，首页无内容，网页控制台报错：Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING。请问有联系方式吗，想学习一下，可偿。邮箱：[471137310@qq.com](mailto:471137310@qq.com),qq同邮
解决了吗老哥

**Comment by EdwardL1u** [comment]
> > 启动项目后，首页无内容，网页控制台报错：Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING。请问有联系方式吗，想学习一下，可偿。邮箱：[471137310@qq.com](mailto:471137310@qq.com),qq同邮
> > 解决了吗老哥

没有，你可以看看怎么解决，互相交流下

**Comment by EdwardL1u** [comment]
> > 启动项目后，首页无内容，网页控制台报错：Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING。请问有联系方式吗，想学习一下，可偿。邮箱：[471137310@qq.com](mailto:471137310@qq.com),qq同邮
> > 解决了吗老哥

我基本解決了问题，还需要的话可以找我

**Comment by Hih314** [comment]
> > > 启动项目后，首页无内容，网页控制台报错：Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING。请问有联系方式吗，想学习一下，可偿。邮箱：[471137310@qq.com](mailto:471137310@qq.com),qq同邮
> > > 解决了吗老哥
> 
> 我基本解決了问题，还需要的话可以找我

大哥，能请教一下吗

**Comment by EdwardL1u** [comment]
> 启动项目后，首页无内容，网页控制台报错：Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING。
